---
title: "Lab11"
subtitle: "Asymptotic Variance"
author: "Piotr Ginalski"
date: "2025-04-14"
output: html_document
---

Today we are going to calculate asymptotic variance.

Let's consider AR(1) model: $X_{n+1} = \alpha X_n + W_{n+1}$

```{r AR1 asymptotic variance}
create_ar1 <- function(n, alpha){
  process <- numeric(n)
  noise <- rnorm(n)
  for(i in (2:n)){
    process[i] <- alpha*process[i - 1] + noise[i]
  }
  return (process)
}


ar1_simulations <- function(n, alpha, n_sim){
  simulations <- numeric(n_sim)
  for (i in (1:n_sim)){
    process <- create_ar1(n, alpha)
    simulations[i] <- mean(process)
  }
  return (simulations)
}
```

```{r alpha = 0}
n <- 2000
alpha <- 0
n_sim <- 10000

realizations <- ar1_simulations(n, alpha, n_sim)
estimator <- n*var(realizations)
estimator
n*mean(realizations^2)

2*sd(n*(realizations^2)) / sqrt(n_sim)
```

```{r alpha = 0.9}
n <- 2000
alpha <- 0.9
n_sim <- 10000

realizations <- ar1_simulations(n, alpha, n_sim)
estimator <- n*var(realizations)
estimator
n*mean(realizations^2)

2*sd(n*(realizations^2)) / sqrt(n_sim)
```

```{r alpha = -0.9}
n <- 2000
alpha <- -0.9
n_sim <- 10000

realizations <- ar1_simulations(n, alpha, n_sim)
estimator <- n*var(realizations)
estimator

2*sd(n*(realizations^2)) / sqrt(n_sim)
```

```{r alpha = 0.99}
n <- 2000
alpha <- 0.99
n_sim <- 100000

realizations <- ar1_simulations(n, alpha, n_sim)
estimator <- n*var(realizations)
estimator

2*sd(n*(realizations^2)) / sqrt(n_sim)
```

```{r alpha = 0.-99}
n <- 2000
alpha <- -0.99
n_sim <- 10000

realizations <- ar1_simulations(n, alpha, n_sim)
estimator <- n*var(realizations)
estimator

2*sd(n*(realizations^2)) / sqrt(n_sim)
```

Metropolis Hasting
```{r metropolis hasting}
a <- 1
n_steps <- 2000
steps <- numeric(n_steps)

for (i in (2:n_steps)){
  prev <- steps[i - 1]
  noise <- runif(prev, -a, a)
}

```