---
title: "Lab13"
subtitle: "Ising Model"
author: "Piotr Ginalski"
date: "2025-06-2"
output: html_document
---

Today, we are going to do 5.3 from lecture notes.
```{r}
d <- 20
map <- matrix(0, d+2, d+2)
alpha0 <-4
alpha1 <- -2
beta <- 1/2
n_sim <- 5000
results <- array(0, dim = c(n_sim, d + 2, d + 2))
burnin <- 1000


## Gibbs
for (sim in (1:n_sim)){
for (i in (2:(d+1))){
  for (j in(2:(d+1))){
    eta <- (beta* (alpha0 +alpha1*(map[i+1, j] + map[i, j+1] + map[i-1, j] + map[i, j-1]) ))
    map[i, j] <- rbinom(1, 1, 1 / (1 + exp(eta)) )
  }
}
results[sim, ,] <- map
}


neighbor_sum <- function(matrix){
  d <- length(matrix[1,])
  sum_all <- 0 
  for (i in (2:(d-1))){
    for (j in (2:(d-1))){
      neighbors <- matrix[i+1, j] + matrix[i, j+1] + matrix[i-1, j] + matrix[i, j-1]
      sum_all <- sum_all + neighbors*matrix[i, j]
    }
  }
  return(sum_all)
}

mean(apply(results[burnin:length(results[,1,1]), , ], 1, sum))
mean(apply(results[burnin:length(results[,1,1]), , ], 1, neighbor_sum))
image(results[1000,,])
```

Let's pack it into function
```{r function}
gibbs_simulation <- function(n_sim, d, alpha0, alpha1, beta, burnin){
  map <- matrix(0, d+2, d+2)
  for (sim in (1:n_sim)){
  for (i in (2:(d+1))){
    for (j in(2:(d+1))){
      eta <- (beta* (alpha0 +alpha1*(map[i+1, j] + map[i, j+1] + map[i-1, j] + map[i, j-1]) ))
    map[i, j] <- rbinom(1, 1, 1 / (1 + exp(eta)) )
  }
}
results[sim, ,] <- map
  }
  return (results[burnin:length(burnin[1, , ])])
}

```