---
title: "Lab 6"
subtitle: "Markov Chains"
author: "Piotr Ginalski"
output: html_notebook
---

In this laboratory, we are going to consider simulating Markov Chain. Let's consider
easy example of Random Walk with absorbing barriers.
```{r random walk with absorbing barriers}
simulate_absorbing_walk <- function(x0, k, p){
  x <- x0
  trajectory <- x0
  while (x > 0 &&  x < k){
    if (runif(1) < p){
      x <- x + 1
      trajectory <- c(trajectory, x)
    }
    else{
      x <- x - 1
      trajectory <- c(trajectory, x)
    }
  }
  return(trajectory)
}


simulate_absorption <- function(x0, k, p, n_sim) {
  count0 <- 0
  countK <- 0
  
  for (i in 1:n_sim) {
    trajectory <- simulate_absorbing_walk(x0, k, p)
    final_state <- trajectory[length(trajectory)]
    if (final_state == 0) {
      count0 <- count0 + 1
    } else {
      countK <- countK + 1
    }
  }
  
  psi0 <- count0 / n_sim
  psiK <- countK / n_sim
  return(c(psi0 = psi0, psiK = psiK))
}

simulate_absorption(5, 20, 0.4, 10^5)
simulate_absorption(15, 20, 0.4, 10^5)

```
And now we create random walk with elastic barriers.
```{r random walk with elastic barriers}
simulate_elastic_barriers_walk <- function(x0, k, p, n){
  x <- x0
  trajectory <- x0
  for (i in 1:n){
    if (runif(1) < p){
      x <- min(x+1, k)
      trajectory <- c(trajectory, x)
    }
    else{
      x <- max(x-1, 0)
      trajectory <- c(trajectory, x)
    }
  }
  return(trajectory)
}

plot(simulate_elastic_barriers_walk(3, 20, 0.5, 30), type = "l")

simulate_asymptotic <- function(x0, k, p, n, x){
  trajectory <- simulate_elastic_barriers_walk(x0, k, p, n)
  visits <- sum(trajectory == x)
  return (visits / n)
}


p <- 0.3
q <- 1 - p
x <- 0
k <- 20


# We can compare our simulation with theoretical formula
print(simulate_asymptotic(x0 = 5, k = 20, p, 10000, x))
print(( (1 - p/q) / (1 - (p/q)^(k+1))) * (p/q)^(x) )
```
Let's do next exercise. We are going to simulate Markov Chain with continuous state space.
```{r simulating markov chain with continuous space}
a <- 0.4
n_time <- 20
x0 <- 0.5

markov_chain_continuous <- function(x0, a, n_time){  
  trajectory <- numeric(n_time + 1)
  trajectory[1] <- x0
  for (i in 2:(n_time + 1)){
  if (runif(1) < a){
    x <- runif(1, min = 0, max = trajectory[i - 1])
    trajectory[i] <- x
  }
  else{
    x <- runif(1, min = trajectory[i - 1], max = 1)
    trajectory[i] <- x
  }
  prev_x <- x
}
return(trajectory)
}

markov_chain_continuous(x0, 0.4, 20)


x0 <- 0.1
{
hist(markov_chain_continuous(x0, 0.4, 200000), probability = TRUE)
curve(dbeta(x, shape1 = 0.6, shape2 = 0.4), add= TRUE)
}

```
As a homework, we can do problem 2.10 from lecture notes.
```{r task 2.10}
n_time <- 20
x0 <- 1/2
a <- 1/3
```